In [1]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [2]:
type(x)

numpy.ndarray

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

# np does element-wise operation
x + y

array([3., 6., 9.])

In [4]:
x * y

array([ 2.,  8., 18.])

In [5]:
x / y

array([0.5, 0.5, 0.5])

In [6]:
# broadcast
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

In [7]:
# matrix representation with np
A = np.array([[1, 2], [3, 4], [0, 0]])
print(A)

[[1 2]
 [3 4]
 [0 0]]


In [8]:
A.shape

(3, 2)

In [9]:
A.dtype

dtype('int64')

In [10]:
B = np.array([[3, 0], [0, 6], [0, 0]])
A + B

array([[ 4,  2],
       [ 3, 10],
       [ 0,  0]])

In [11]:
# element-wise product
A * B

array([[ 3,  0],
       [ 0, 24],
       [ 0,  0]])

In [12]:
# broadcast
A * 10

array([[10, 20],
       [30, 40],
       [ 0,  0]])

In [13]:
# broadcast
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [14]:
# how to access elements
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [15]:
X[0]

array([51, 55])

In [16]:
X[0][1]

55

In [17]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [18]:
X = X.flatten()

In [19]:
print(X)

[51 55 14 19  0  4]


In [20]:
# get elements 
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [21]:
X > 15

array([ True,  True, False,  True, False, False])

In [22]:
X[X>15]

array([51, 55, 19])